// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCDo5G2NXOAGcGkjwoU1xLGH8ow0lPGo',
    appId: '1:368815703592:web:8b09953113a79cb783171d',
    messagingSenderId: '368815703592',
    projectId: 'oncoguide-bf10c',
    authDomain: 'oncoguide-bf10c.firebaseapp.com',
    storageBucket: 'oncoguide-bf10c.firebasestorage.app',
    measurementId: 'G-YJ8EJ9C5C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFoAxxxxzC8eSoKnNUeQ8xskJjsZS-U5Q',
    appId: '1:368815703592:android:2e46f474b7cb65d583171d',
    messagingSenderId: '368815703592',
    projectId: 'oncoguide-bf10c',
    storageBucket: 'oncoguide-bf10c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5coM4DNhCtC7DaNQ5NGSqx2_kt744gIM',
    appId: '1:368815703592:ios:4de3a67f0e3658f183171d',
    messagingSenderId: '368815703592',
    projectId: 'oncoguide-bf10c',
    storageBucket: 'oncoguide-bf10c.firebasestorage.app',
    iosBundleId: 'com.example.oncoguideFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5coM4DNhCtC7DaNQ5NGSqx2_kt744gIM',
    appId: '1:368815703592:ios:4de3a67f0e3658f183171d',
    messagingSenderId: '368815703592',
    projectId: 'oncoguide-bf10c',
    storageBucket: 'oncoguide-bf10c.firebasestorage.app',
    iosBundleId: 'com.example.oncoguideFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOCDo5G2NXOAGcGkjwoU1xLGH8ow0lPGo',
    appId: '1:368815703592:web:c05cba998b297f0583171d',
    messagingSenderId: '368815703592',
    projectId: 'oncoguide-bf10c',
    authDomain: 'oncoguide-bf10c.firebaseapp.com',
    storageBucket: 'oncoguide-bf10c.firebasestorage.app',
    measurementId: 'G-DRNJXXE7GM',
  );
}
